### ISSUE TITLE
Need to properly handle Unit8Array

### ISSUE THREAD

**Issue by RadND** [openpgpjs/web-stream-tools#27]
Browser: Firefox 112

When trying use `openpgpjs.readMessage({ armoredMessage: myFile.stream()})` reading a file contain an armor text message (`-----BEGIN PGP MESSAGE-----`) I always got wrong format error. 
After poking around I found out it is because at [reader.js line97](https://github.com/openpgpjs/web-stream-tools/blob/79be1a3a3193be0d56242d66edae9c52adee799e/lib/reader.js#LL97C4-L97C4) 
value:Unit8Array from filereader turn to a number array litiral string (`[56,78,90,133,42]`)

my temp solution is
```
+ if(value instanceof Uint8Array){
+      value = new TextDecoder('utf-8').decode(value);
+ }
value += '';
```

**Comment by larabr** [comment]
`armoredMessage` expects a string (or streamed string). If you have armored data in non-string format e.g. due to the way you read your file, you need to decode it before passing it to `armoredMessage`.
